ALTER TABLE branches ADD COLUMN status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'SUSPENDED', 'REMOVED'));

UPDATE branches
SET status = CASE WHEN active = 1 THEN 'ACTIVE' ELSE 'REMOVED' END;
